name: Build

on:
    push:
        branches: [master]
    schedule:
        -   cron: '30 5 8 * *'

jobs:

    tests:
        name: Docker
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['8.1', '8.2']
                icu: ['70.1', '71.1']

        steps:
            -   name: Checkout
                uses: actions/checkout@v3

            -   name: Determine the version
                id: version
                run: |
                    VERSION="$PHP_VERSION-$ICU_VERSION"
                    DOCKER_TAGS=jakzal/php-intl:$VERSION

                    echo "Version: $VERSION"
                    echo "Docker tags: $DOCKER_TAGS"
                    echo "version=${VERSION}" >> $GITHUB_OUTPUT
                    echo "tags=${DOCKER_TAGS}" >> $GITHUB_OUTPUT
                env:
                    PHP_VERSION: ${{ matrix.php }}
                    ICU_VERSION: ${{ matrix.icu }}

            -   name: Set up Docker Buildx
                uses: docker/setup-buildx-action@v2

            -   name: Login to DockerHub
                uses: docker/login-action@v2
                with:
                    username: jakzal
                    password: ${{ secrets.DOCKER_HUB_TOKEN }}

            -   name: Build
                uses: docker/build-push-action@v3
                with:
                    push: true
                    platforms: linux/amd64
                    tags: ${{ steps.version.outputs.tags }}
                    labels: |
                        org.opencontainers.image.source=${{ github.event.repository.html_url }}
                        org.opencontainers.image.revision=${{ github.sha }}
                    cache-from: type=gha,scope=${{ github.workflow }}-${{ matrix.php }}-${{ matrix.icu }}
                    cache-to: type=gha,scope=${{ github.workflow }}-${{ matrix.php }}-${{ matrix.icu }},mode=max

            -   name: Verify
                run: |
                    docker run --rm jakzal/php-intl:${{ matrix.php }}-${{ matrix.icu }} sh -c "icu-config --version && php -i | grep 'ICU version'"
                    docker images
