name: Build

on:
    push:
    pull_request:

jobs:

    tests:
        name: Docker
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php: ['8.0']
                icu: ['68.2']

        steps:
            -   name: Checkout
                uses: actions/checkout@v2

            -   name: Build the image
                run: |
                    make build ICU_VERSION=${{ matrix.icu }} PHP_VERSION=${{ matrix.php }}
                    docker run --rm jakzal/php-intl:${{ matrix.php }}-${{ matrix.icu }} sh -c "icu-config --version && php -i | grep 'ICU version'"
                    docker images
